spring.application.name=SpringSecurity
server.port=8081

spring.security.user.name=vaibhav
spring.security.user.password=1371

spring.datasource.url=jdbc:postgresql://localhost:5432/Vaibhav
spring.datasource.username=postgres
spring.datasource.password=Vaibhav@1371
